name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  buildJava:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup jdk-17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'
    - name: building
      uses: actions/setup-java@main
      run: javac src/BookingMain.java

  buildPython:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: demo-run
      run: |
        echo "Dummy data used to test"
        python src/new.py

  publish:
    needs: [buildJava, buildPython]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        SUPER_SECRET: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u dipugodocker -p "$SUPER_SECRET"
        docker build --target=java-dev -t dipugodocker/airplane-jdk:v1 .
        docker build --target=image-builder -t dipugodocker/airplane-img:v1 .
        docker push dipugodocker/airplane-jdk:v1
        docker push dipugodocker/airplane-img:v1